--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/BreathTakinglyBinary/Skylands
branches:
- master
projects:
  Skylands:
    path: ""
    libs:
    - src: BreathTakinglyBinary/libDynamicForms/libDynamicForms
      version: ^1.1.0
    - src: CortextPE/Commando/Commando
        version: ^0.5.0
...